name = "AoC"
version = "0.1.0"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "AoC"

[[lean_exe]]
name = "aoc2024_01"
root = "Day01.Main"

[[lean_exe]]
name = "aoc2024_02"
root = "Day02.Main"

[[lean_exe]]
name = "aoc2024_03"
root = "Day03.Main"

[[lean_exe]]
name = "aoc2024_04"
root = "Day04.Main"

[[lean_exe]]
name = "aoc2024_05"
root = "Day05.Main"

[[lean_exe]]
name = "aoc2024_06"
root = "Day06.Main"

[[lean_exe]]
name = "aoc2024_07"
root = "Day07.Main"

[[lean_exe]]
name = "aoc2024_10"
root = "Day10.Main"
