name = "AoC2024"
version = "0.1.0"
defaultTargets = ["aoc2024_01"]

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[lean_lib]]
name = "AoC2024"

[[lean_exe]]
name = "aoc2024_01"
root = "Day01.Main"
