name = "AoC2024"
version = "0.1.0"
defaultTargets = ["aoc2024_01"]

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "main"

[[lean_lib]]
name = "AoC2024"

[[lean_exe]]
name = "aoc2024_01"
root = "Day01.Main"

[[lean_exe]]
name = "aoc2024_02"
root = "Day02.Main"

[[lean_exe]]
name = "aoc2024_03"
root = "Day03.Main"
